const pool = require("../db/db");


module.exports = {
  insertThesisToDB,
  getUnderAssignment,
  getRelevantThesis,
  searchStudents,
  getAvailableTopics,
  assignThesisToStudent,
  getTemporaryAssignments,
  cancelActiveThesisAssignment,
  cancelThesisUnderAssignment,
  updateThesis,
  getProfessorInvitations,
  acceptInvitation,
  rejectInvitation,
  leaveComittee,
  getThesisTimeline,
  deleteThesis,
  getInstructorStatistics,
  getSpecificThesis,
  getThesisInvitations,
  getProfessorNotesForThesis,
  addNoteForThesis,
  editNote,
  deleteNote,
  getProfessorRole,
  getAssignmentDate,
  markUnderReview,
  getDraftFilename,
  getPresentationDate,
  createPresentationAnnouncement,
  getPresentationAnnouncement,
  enableGrading,
  getGradingStatus,
  getGrades,
  saveProfessorGrade
};

